### ISSUE TITLE
2.8 fails to build with cmake on Linux

### ISSUE THREAD

**Issue by toconnor** [akheron/jansson#306]
When following the build instructions for using CMake to build jansson, release 2.8 no longer builds on Linux, whereas prior releases did. The compiler complains about `json_int_t` being an unknown type. I suspect the change in support of issue #209 introduced this build regression.

```
Scanning dependencies of target jansson
[  2%] Building C object CMakeFiles/jansson.dir/src/dump.c.o
In file included from /tmp/jansson-2.8/src/dump.c:17:0:
/tmp/jansson-2.8/src/jansson.h:90:22: error: unknown type name 'json_int_t'
 json_t *json_integer(json_int_t value);
```

**Comment by akheron** [comment]
Fixed, thanks. I'll release 2.8.1 when I have time.

**Comment by buhl** [comment]
Sorry to comment on a closed issue, but I do not think it has been resolved.

I still can not compile anything above branch 2.7 on linux after using cmake.
I did a git bisect to be sure there was nothing else affecting this and it pointed to 1c38ab17f5ab7e5f555b134fbb48eec049f383f1
It looks like it is indeed the fix in #209 still causing problems for me
On master reverting the changes
```diff
diff --git a/src/jansson.h b/src/jansson.h
index b5a4d15..0659358 100644
--- a/src/jansson.h
+++ b/src/jansson.h
@@ -12,7 +12,7 @@
 #include <stdlib.h>  /* for size_t */
 #include <stdarg.h>

-#include "jansson_config.h"
+#include <jansson_config.h>

 #ifdef __cplusplus
 extern "C" {
```
fixes the make problems.


I can compile the source code without problems when using the autoconf script

**Comment by akheron** [comment]
This happens because you've built Jansson first with autotools, and then try with CMake. Try removing `src/jansson_config.h` and building with CMake again.

**Comment by buhl** [comment]
You are completely right. Sorry for wasting your time.
